server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.ijxtsqdneuqqtintdsyb
    password: wearweather1234!

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # ?? ???? update? ???, ??? ??? ??? none?? validate? ??? ?? ?????.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true